server:
  port: 8088
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.92.129:5810/foodie-shop-dev?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  redis:
    database: 0
    host: 192.168.92.129
    port: 6379
    password:
  hikari:
    connection-timeout: 30000 #等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生
    SQminimum-idle: 5 #最小连接数
    maximum-pool-size: 20 #最大连接数
    auto-commit: true #自动提交
    idle-timeout: 600000 #连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
    pool-name: DateSourceHikariCP #连接池名字
    max-lifetime: 1800000 #连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
    connection-test-query: SELECT1

##############################################################mybatis配置#############################################################
mybatis:
  type-aliases-package: com.lucky.pojo #所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml #mapper映射文件
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  # 分页插件配置
pagehelper:
  support-methods-arguments: true
  helper-dialect: mysql
